<?php


 function autoload_a59a0e7c0ce3bbe9293527015f17d5b6($class)
{
    $classes = array(
        'TNWebService' => __DIR__ .'/TNWebService.php',
        'ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'ArrayOfUri' => __DIR__ .'/ArrayOfUri.php',
        'serviceAuth' => __DIR__ .'/serviceAuth.php',
        'getProductsList' => __DIR__ .'/getProductsList.php',
        'getProductsListResponse' => __DIR__ .'/getProductsListResponse.php',
        'ArrayOfProductEntity' => __DIR__ .'/ArrayOfProductEntity.php',
        'ProductEntity' => __DIR__ .'/ProductEntity.php',
        'ArrayOfProductShippingPlaceUnitAdjustment' => __DIR__ .'/ArrayOfProductShippingPlaceUnitAdjustment.php',
        'ProductShippingPlaceUnitAdjustment' => __DIR__ .'/ProductShippingPlaceUnitAdjustment.php',
        'ArrayOfProductMeasureUnit' => __DIR__ .'/ArrayOfProductMeasureUnit.php',
        'ProductMeasureUnit' => __DIR__ .'/ProductMeasureUnit.php',
        'ArrayOfProductWeightAdjustment' => __DIR__ .'/ArrayOfProductWeightAdjustment.php',
        'ProductWeightAdjustment' => __DIR__ .'/ProductWeightAdjustment.php',
        'ArrayOfProductAttributeValue' => __DIR__ .'/ArrayOfProductAttributeValue.php',
        'ProductAttributeValue' => __DIR__ .'/ProductAttributeValue.php',
        'getProductsGroups' => __DIR__ .'/getProductsGroups.php',
        'getProductsGroupsResponse' => __DIR__ .'/getProductsGroupsResponse.php',
        'ArrayOfProductGroup' => __DIR__ .'/ArrayOfProductGroup.php',
        'ProductGroup' => __DIR__ .'/ProductGroup.php',
        'getProductsAttributes' => __DIR__ .'/getProductsAttributes.php',
        'getProductsAttributesResponse' => __DIR__ .'/getProductsAttributesResponse.php',
        'ArrayOfProductAttribute' => __DIR__ .'/ArrayOfProductAttribute.php',
        'ProductAttribute' => __DIR__ .'/ProductAttribute.php',
        'ArrayOfProductAttributeOption' => __DIR__ .'/ArrayOfProductAttributeOption.php',
        'ProductAttributeOption' => __DIR__ .'/ProductAttributeOption.php',
        'ProductAttributeType' => __DIR__ .'/ProductAttributeType.php',
        'getProductsPrices' => __DIR__ .'/getProductsPrices.php',
        'getChangedProductsPrices' => __DIR__ .'/getChangedProductsPrices.php',
        'getProductsPricesResponse' => __DIR__ .'/getProductsPricesResponse.php',
        'ArrayOfProductPrice' => __DIR__ .'/ArrayOfProductPrice.php',
        'ProductPrice' => __DIR__ .'/ProductPrice.php',
        'getProductsStock' => __DIR__ .'/getProductsStock.php',
        'getChangedProductsStock' => __DIR__ .'/getChangedProductsStock.php',
        'getProductsStockResponse' => __DIR__ .'/getProductsStockResponse.php',
        'ArrayOfProductStock' => __DIR__ .'/ArrayOfProductStock.php',
        'ProductStock' => __DIR__ .'/ProductStock.php',
        'getLoadingRates' => __DIR__ .'/getLoadingRates.php',
        'getLoadingRatesResponse' => __DIR__ .'/getLoadingRatesResponse.php',
        'ArrayOfLoadingRate' => __DIR__ .'/ArrayOfLoadingRate.php',
        'LoadingRate' => __DIR__ .'/LoadingRate.php',
        'getQtyRestrictions' => __DIR__ .'/getQtyRestrictions.php',
        'getQtyRestrictionsResponse' => __DIR__ .'/getQtyRestrictionsResponse.php',
        'ArrayOfQtyRestriction' => __DIR__ .'/ArrayOfQtyRestriction.php',
        'QtyRestriction' => __DIR__ .'/QtyRestriction.php',
        'QtyRestrictionRule' => __DIR__ .'/QtyRestrictionRule.php',
        'getTransports' => __DIR__ .'/getTransports.php',
        'getTransportsResponse' => __DIR__ .'/getTransportsResponse.php',
        'ArrayOfTransport' => __DIR__ .'/ArrayOfTransport.php',
        'Transport' => __DIR__ .'/Transport.php',
        'getTransportLoadingMethods' => __DIR__ .'/getTransportLoadingMethods.php',
        'getTransportLoadingMethodsResponse' => __DIR__ .'/getTransportLoadingMethodsResponse.php',
        'ArrayOfTransportLoadingMethod' => __DIR__ .'/ArrayOfTransportLoadingMethod.php',
        'TransportLoadingMethod' => __DIR__ .'/TransportLoadingMethod.php',
        'getCities' => __DIR__ .'/getCities.php',
        'getCitiesResponse' => __DIR__ .'/getCitiesResponse.php',
        'ArrayOfCity' => __DIR__ .'/ArrayOfCity.php',
        'City' => __DIR__ .'/City.php',
        'getProductSchedulingTechniques' => __DIR__ .'/getProductSchedulingTechniques.php',
        'getProductSchedulingTechniquesResponse' => __DIR__ .'/getProductSchedulingTechniquesResponse.php',
        'ArrayOfProductSchedulingTechnique' => __DIR__ .'/ArrayOfProductSchedulingTechnique.php',
        'ProductSchedulingTechnique' => __DIR__ .'/ProductSchedulingTechnique.php',
        'getSchedulingTechniques' => __DIR__ .'/getSchedulingTechniques.php',
        'getSchedulingTechniquesResponse' => __DIR__ .'/getSchedulingTechniquesResponse.php',
        'ArrayOfSchedulingTechnique' => __DIR__ .'/ArrayOfSchedulingTechnique.php',
        'SchedulingTechnique' => __DIR__ .'/SchedulingTechnique.php',
        'getMeasureUnits' => __DIR__ .'/getMeasureUnits.php',
        'getMeasureUnitsResponse' => __DIR__ .'/getMeasureUnitsResponse.php',
        'ArrayOfMeasureUnit' => __DIR__ .'/ArrayOfMeasureUnit.php',
        'MeasureUnit' => __DIR__ .'/MeasureUnit.php',
        'getPretensionStatuses' => __DIR__ .'/getPretensionStatuses.php',
        'getPretensionStatusesResponse' => __DIR__ .'/getPretensionStatusesResponse.php',
        'ArrayOfPretensionStatus' => __DIR__ .'/ArrayOfPretensionStatus.php',
        'PretensionStatus' => __DIR__ .'/PretensionStatus.php',
        'getWarehouses' => __DIR__ .'/getWarehouses.php',
        'getWarehousesResponse' => __DIR__ .'/getWarehousesResponse.php',
        'ArrayOfWarehouse' => __DIR__ .'/ArrayOfWarehouse.php',
        'Warehouse' => __DIR__ .'/Warehouse.php',
        'submitContrapartyObject' => __DIR__ .'/submitContrapartyObject.php',
        'Contraparty' => __DIR__ .'/Contraparty.php',
        'submitOrderObject' => __DIR__ .'/submitOrderObject.php',
        'ArrayOfOrderAddress' => __DIR__ .'/ArrayOfOrderAddress.php',
        'OrderAddress' => __DIR__ .'/OrderAddress.php',
        'ArrayOfOrderItem' => __DIR__ .'/ArrayOfOrderItem.php',
        'OrderItem' => __DIR__ .'/OrderItem.php',
        'ArrayOfOrderService' => __DIR__ .'/ArrayOfOrderService.php',
        'OrderService' => __DIR__ .'/OrderService.php',
        'OrderPlanStatus' => __DIR__ .'/OrderPlanStatus.php',
        'OrderPlanStatusValue' => __DIR__ .'/OrderPlanStatusValue.php',
        'ArrayOfOrderPlanStatusItem' => __DIR__ .'/ArrayOfOrderPlanStatusItem.php',
        'OrderPlanStatusItem' => __DIR__ .'/OrderPlanStatusItem.php',
        'ArrayOfOrderPlanStatusService' => __DIR__ .'/ArrayOfOrderPlanStatusService.php',
        'OrderPlanStatusService' => __DIR__ .'/OrderPlanStatusService.php',
        'submitPlanningDepartmentRequest' => __DIR__ .'/submitPlanningDepartmentRequest.php',
        'PlanningDepartmentAnswer' => __DIR__ .'/PlanningDepartmentAnswer.php',
        'ArrayOfPlanningDepartmentAnswerItem' => __DIR__ .'/ArrayOfPlanningDepartmentAnswerItem.php',
        'PlanningDepartmentAnswerItem' => __DIR__ .'/PlanningDepartmentAnswerItem.php',
        'getOrderPurchaseGuaranteeStatusObject' => __DIR__ .'/getOrderPurchaseGuaranteeStatusObject.php',
        'getOrderPurchaseGuaranteeStatusResponseObject' => __DIR__ .'/getOrderPurchaseGuaranteeStatusResponseObject.php',
        'submitOrderDeliveryInfoObject' => __DIR__ .'/submitOrderDeliveryInfoObject.php',
        'ArrayOfOrderDeliveryAddress' => __DIR__ .'/ArrayOfOrderDeliveryAddress.php',
        'OrderDeliveryAddress' => __DIR__ .'/OrderDeliveryAddress.php',
        'allowOrderDeliveryObject' => __DIR__ .'/allowOrderDeliveryObject.php',
        'OrderDeliveryAllowance' => __DIR__ .'/OrderDeliveryAllowance.php',
        'submitBankTransferOrderObject' => __DIR__ .'/submitBankTransferOrderObject.php',
        'BankTransferOrder' => __DIR__ .'/BankTransferOrder.php',
        'OrderPaymentType' => __DIR__ .'/OrderPaymentType.php',
        'getOrderDeliveryProgressObject' => __DIR__ .'/getOrderDeliveryProgressObject.php',
        'getOrderDeliveryProgressResponseObject' => __DIR__ .'/getOrderDeliveryProgressResponseObject.php',
        'getOrderDeliveryCompletionObject' => __DIR__ .'/getOrderDeliveryCompletionObject.php',
        'getOrderDeliveryCompletionResponseObject' => __DIR__ .'/getOrderDeliveryCompletionResponseObject.php',
        'cancelOrderObject' => __DIR__ .'/cancelOrderObject.php',
        'OrderCancellation' => __DIR__ .'/OrderCancellation.php',
        'disallowOrderDeliveryObject' => __DIR__ .'/disallowOrderDeliveryObject.php',
        'OrderDeliveryDisallowance' => __DIR__ .'/OrderDeliveryDisallowance.php',
        'submitOutflowRequestObject' => __DIR__ .'/submitOutflowRequestObject.php',
        'OutflowStatus' => __DIR__ .'/OutflowStatus.php',
        'submitPretensionObject' => __DIR__ .'/submitPretensionObject.php',
        'Pretension' => __DIR__ .'/Pretension.php',
        'getPretensionStatusObject' => __DIR__ .'/getPretensionStatusObject.php',
        'getPretensionStatusResponseObject' => __DIR__ .'/getPretensionStatusResponseObject.php',
        'getRequestStatusObject' => __DIR__ .'/getRequestStatusObject.php',
        'getRequestStatusResponseObject' => __DIR__ .'/getRequestStatusResponseObject.php',
        'RequestStatusResponse' => __DIR__ .'/RequestStatusResponse.php',
        'StatusResponseState' => __DIR__ .'/StatusResponseState.php',
        'submittedRequest' => __DIR__ .'/submittedRequest.php',
        'OperationFault' => __DIR__ .'/OperationFault.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_a59a0e7c0ce3bbe9293527015f17d5b6');

// Do nothing. The rest is just leftovers from the code generation.
{
}
